config/routes.rb
Rails.application.routes.draw do

  root 'attendances#index'
  
  devise_for :users
  resources :users
  resources :receipts
  resources :enterprises
  resources :attendances
  resources :items
  resources :device_ids
  resources :account_types
  resources :payment_methods
  resources :attendance_statuses
  resources :attendance_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
end

app/controllers/payment_methods_controller.rb
class PaymentMethodsController < ApplicationController
  before_action :set_payment_method, only: [:show, :edit, :update, :destroy]

  # GET /payment_methods
  # GET /payment_methods.json
  def index
    @payment_methods = PaymentMethod.all
  end

  # GET /payment_methods/1
  # GET /payment_methods/1.json
  def show
  end

  # GET /payment_methods/new
  def new
    @payment_method = PaymentMethod.new
  end

  # GET /payment_methods/1/edit
  def edit
  end

  # POST /payment_methods
  # POST /payment_methods.json
  def create
    @payment_method = PaymentMethod.new(payment_method_params)

    respond_to do |format|
      if @payment_method.save
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully created.' }
        format.json { render :show, status: :created, location: @payment_method }
      else
        format.html { render :new }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payment_methods/1
  # PATCH/PUT /payment_methods/1.json
  def update
    respond_to do |format|
      if @payment_method.update(payment_method_params)
        format.html { redirect_to @payment_method, notice: 'Payment method was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment_method }
      else
        format.html { render :edit }
        format.json { render json: @payment_method.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payment_methods/1
  # DELETE /payment_methods/1.json
  def destroy
    @payment_method.destroy
    respond_to do |format|
      format.html { redirect_to payment_methods_url, notice: 'Payment method was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment_method
      @payment_method = PaymentMethod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_method_params
      params.require(:payment_method).permit(:name, :)
    end
end

app/helpers/payment_methods_helper.rb
module PaymentMethodsHelper
end

app/views/payment_methods/_form.html.erb
<%= form_for(payment_method) do |f| %>
  <% if payment_method.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment_method.errors.count, "error") %> prohibited this payment_method from being saved:</h2>

      <ul>
      <% payment_method.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label : %>
    <%= f.text_field : %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/payment_methods/edit.html.erb
<h1>Editing Payment Method</h1>

<%= render 'form', payment_method: @payment_method %>

<%= link_to 'Show', @payment_method %> |
<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payment Methods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payment_methods.each do |payment_method| %>
      <tr>
        <td><%= payment_method.name %></td>
        <td><%= payment_method. %></td>
        <td><%= link_to 'Show', payment_method %></td>
        <td><%= link_to 'Edit', edit_payment_method_path(payment_method) %></td>
        <td><%= link_to 'Destroy', payment_method, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment Method', new_payment_method_path %>

app/views/payment_methods/new.html.erb
<h1>New Payment Method</h1>

<%= render 'form', payment_method: @payment_method %>

<%= link_to 'Back', payment_methods_path %>

app/views/payment_methods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @payment_method.name %>
</p>

<p>
  <strong>:</strong>
  <%= @payment_method. %>
</p>

<%= link_to 'Edit', edit_payment_method_path(@payment_method) %> |
<%= link_to 'Back', payment_methods_path %>