config/routes.rb
Rails.application.routes.draw do

  root 'attendances#index'
  
  devise_for :users
  resources :users
  resources :receipts
  resources :enterprises
  resources :attendances
  resources :items
  resources :device_ids
  resources :account_types
  resources :payment_methods
  resources :attendance_statuses
  resources :attendance_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/attendance_statuses_controller.rb
class AttendanceStatusesController < ApplicationController
  before_action :set_attendance_status, only: [:show, :edit, :update, :destroy]

  # GET /attendance_statuses
  # GET /attendance_statuses.json
  def index
    @attendance_statuses = AttendanceStatus.all
  end

  # GET /attendance_statuses/1
  # GET /attendance_statuses/1.json
  def show
  end

  # GET /attendance_statuses/new
  def new
    @attendance_status = AttendanceStatus.new
  end

  # GET /attendance_statuses/1/edit
  def edit
  end

  # POST /attendance_statuses
  # POST /attendance_statuses.json
  def create
    @attendance_status = AttendanceStatus.new(attendance_status_params)

    respond_to do |format|
      if @attendance_status.save
        format.html { redirect_to @attendance_status, notice: 'Attendance status was successfully created.' }
        format.json { render :show, status: :created, location: @attendance_status }
      else
        format.html { render :new }
        format.json { render json: @attendance_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /attendance_statuses/1
  # PATCH/PUT /attendance_statuses/1.json
  def update
    respond_to do |format|
      if @attendance_status.update(attendance_status_params)
        format.html { redirect_to @attendance_status, notice: 'Attendance status was successfully updated.' }
        format.json { render :show, status: :ok, location: @attendance_status }
      else
        format.html { render :edit }
        format.json { render json: @attendance_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attendance_statuses/1
  # DELETE /attendance_statuses/1.json
  def destroy
    @attendance_status.destroy
    respond_to do |format|
      format.html { redirect_to attendance_statuses_url, notice: 'Attendance status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_attendance_status
      @attendance_status = AttendanceStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def attendance_status_params
      params.require(:attendance_status).permit(:name, :string)
    end
end

app/helpers/attendance_statuses_helper.rb
module AttendanceStatusesHelper
end

app/views/attendance_statuses/_form.html.erb
<%= form_for(attendance_status) do |f| %>
  <% if attendance_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(attendance_status.errors.count, "error") %> prohibited this attendance_status from being saved:</h2>

      <ul>
      <% attendance_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :string %>
    <%= f.text_field :string %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/attendance_statuses/edit.html.erb
<h1>Editing Attendance Status</h1>

<%= render 'form', attendance_status: @attendance_status %>

<%= link_to 'Show', @attendance_status %> |
<%= link_to 'Back', attendance_statuses_path %>

app/views/attendance_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Attendance Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>String</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @attendance_statuses.each do |attendance_status| %>
      <tr>
        <td><%= attendance_status.name %></td>
        <td><%= attendance_status.string %></td>
        <td><%= link_to 'Show', attendance_status %></td>
        <td><%= link_to 'Edit', edit_attendance_status_path(attendance_status) %></td>
        <td><%= link_to 'Destroy', attendance_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Attendance Status', new_attendance_status_path %>

app/views/attendance_statuses/new.html.erb
<h1>New Attendance Status</h1>

<%= render 'form', attendance_status: @attendance_status %>

<%= link_to 'Back', attendance_statuses_path %>

app/views/attendance_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @attendance_status.name %>
</p>

<p>
  <strong>String:</strong>
  <%= @attendance_status.string %>
</p>

<%= link_to 'Edit', edit_attendance_status_path(@attendance_status) %> |
<%= link_to 'Back', attendance_statuses_path %>