config/routes.rb
Rails.application.routes.draw do

  root 'attendances#index'
  
  devise_for :users
  resources :users
  resources :receipts
  resources :enterprises
  resources :attendances
  resources :items
  resources :device_ids
  resources :account_types
  resources :payment_methods
  resources :attendance_statuses
  resources :attendance_types
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  belongs_to :item
  belongs_to :enterprise
  belongs_to :attendance
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  before_action :set_receipt, only: [:show, :edit, :update, :destroy]

  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = Receipt.all
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
  end

  # GET /receipts/new
  def new
    @receipt = Receipt.new
  end

  # GET /receipts/1/edit
  def edit
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = Receipt.new(receipt_params)

    respond_to do |format|
      if @receipt.save
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render :show, status: :created, location: @receipt }
      else
        format.html { render :new }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /receipts/1
  # PATCH/PUT /receipts/1.json
  def update
    respond_to do |format|
      if @receipt.update(receipt_params)
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @receipt }
      else
        format.html { render :edit }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt.destroy
    respond_to do |format|
      format.html { redirect_to receipts_url, notice: 'Receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_receipt
      @receipt = Receipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def receipt_params
      params.require(:receipt).permit(:date, :address, :vendor_id, :client_id, :total, :item_id, :enterprise_id)
    end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/views/receipts/_form.html.erb
<%= form_for(receipt) do |f| %>
  <% if receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% receipt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.datetime_select :date %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :vendor_id %>
    <%= f.number_field :vendor_id %>
  </div>

  <div class="field">
    <%= f.label :client_id %>
    <%= f.number_field :client_id %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.text_field :total %>
  </div>

  <div class="field">
    <%= f.label :item_id %>
    <%= f.text_field :item_id %>
  </div>

  <div class="field">
    <%= f.label :enterprise_id %>
    <%= f.text_field :enterprise_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<h1>Editing Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Show', @receipt %> |
<%= link_to 'Back', receipts_path %>

app/views/receipts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Receipts</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Address</th>
      <th>Vendor</th>
      <th>Client</th>
      <th>Total</th>
      <th>Item</th>
      <th>Enterprise</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @receipts.each do |receipt| %>
      <tr>
        <td><%= receipt.date %></td>
        <td><%= receipt.address %></td>
        <td><%= receipt.vendor_id %></td>
        <td><%= receipt.client_id %></td>
        <td><%= receipt.total %></td>
        <td><%= receipt.item %></td>
        <td><%= receipt.enterprise %></td>
        <td><%= link_to 'Show', receipt %></td>
        <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
        <td><%= link_to 'Destroy', receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Receipt', new_receipt_path %>

app/views/receipts/new.html.erb
<h1>New Receipt</h1>

<%= render 'form', receipt: @receipt %>

<%= link_to 'Back', receipts_path %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @receipt.date %>
</p>

<p>
  <strong>Address:</strong>
  <%= @receipt.address %>
</p>

<p>
  <strong>Vendor:</strong>
  <%= @receipt.vendor_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @receipt.client_id %>
</p>

<p>
  <strong>Total:</strong>
  <%= @receipt.total %>
</p>

<p>
  <strong>Item:</strong>
  <%= @receipt.item %>
</p>

<p>
  <strong>Enterprise:</strong>
  <%= @receipt.enterprise %>
</p>

<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back', receipts_path %>